# Generated by Django 5.1.6 on 2026-01-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10)),
                ('duration', models.FloatField(help_text='Duration from parent node')),
                ('node_type', models.CharField(choices=[('root', 'Root'), ('left', 'Left'), ('right', 'Right')], default='root', max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='flight.flightnode')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flight.route')),
            ],
            options={
                'unique_together': {('parent', 'node_type')},
            },
        ),
    ]
